const SITE='https://www.vaelithlabs.com.br';
const GOOGLE_ADS_ID='AW-18446080841';
const esc=(v='')=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const navItems=[['engenharia','Engenharia'],['arquitetura','Arquitetura'],['construcao','Construção'],['tecnologia','Tecnologia'],['infraestrutura','Infraestrutura'],['mercado','Mercado'],['gestao','Gestão'],['sustentabilidade','Sustentabilidade']];
const mark=`<svg class="mark" viewBox="220 250 820 700" aria-hidden="true"><path d="M240 276H332L632 787L938 276H1022L632 923Z" fill="currentColor"/><path d="M434 276H852L661 598H580L730 344H474Z" fill="currentColor"/></svg>`;
const brand=`<span class="brand">${mark}<span class="wordmark">VAELITH</span></span>`;
const googleTag=`<script async src="https://www.googletagmanager.com/gtag/js?id=${GOOGLE_ADS_ID}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','${GOOGLE_ADS_ID}');</script>`;
function header(active=''){
  const nav=navItems.map(([slug,name])=>`<a href="/categoria/${slug}" class="${active===slug?'active':''}">${name}</a>`).join('');
  return `<header class="site-header" id="siteHeader"><div class="container masthead"><a class="brand-link" href="/" aria-label="VAELITH — início">${brand}</a><div class="utility-nav"><a href="/arquivo">Arquivo</a><a href="/eventos">Agenda</a><a href="/sobre">Sobre</a><a class="search-link" href="/buscar" aria-label="Buscar no VAELITH">Buscar</a></div><button class="menu-btn" id="menuBtn" type="button" aria-controls="mainNav" aria-expanded="false">Menu</button></div><nav class="navbar" id="mainNav" aria-label="Navegação principal"><div class="container"><a href="/" class="${active==='home'?'active':''}">Início</a>${nav}<a href="/artigos-cientificos" class="${active==='research'?'active':''}">Pesquisa & Ciência</a><a href="/eventos" class="${active==='eventos'?'active':''}">Agenda</a></div></nav></header>`;
}
function newsletter(){return `<section class="newsletter-band" aria-label="Newsletter VAELITH"><div class="container newsletter-grid"><div><div class="eyebrow">VAELITH Briefing</div><h2>As principais notícias do setor, todos os dias.</h2><p>Uma seleção objetiva de engenharia, construção, infraestrutura, arquitetura, mercado, gestão, sustentabilidade e tecnologia.</p></div><form class="newsletter-form" action="/api/newsletter" method="post"><label class="sr-only" for="newsletter-email">Seu e-mail</label><div class="newsletter-fields"><input id="newsletter-email" name="email" type="email" autocomplete="email" placeholder="seuemail@empresa.com" required><button type="submit">Assinar</button></div><label class="newsletter-consent"><input type="checkbox" name="consent" value="yes" required><span>Concordo em receber o briefing diário e posso cancelar a qualquer momento.</span></label></form></div></section>`}
function footer(){return `${newsletter()}<footer class="footer"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="/" aria-label="VAELITH — início">${brand}</a><p>Engenharia, construção, infraestrutura e tecnologia em perspectiva.</p></div><div><h4>Navegação</h4><p><a href="/arquivo">Arquivo de notícias</a><br><a href="/artigos-cientificos">Pesquisa & Ciência</a><br><a href="/sobre">Sobre</a><br><a href="/politica-editorial">Política editorial</a><br><a href="/privacidade">Privacidade</a><br><a href="/midia-kit">Mídia kit</a></p></div><div><h4>Contato</h4><p><a href="mailto:labsvaelith@gmail.com">labsvaelith@gmail.com</a></p></div></div><div class="footer-bottom"><span>© 2026 VAELITH LABS</span><span>Todos os direitos reservados.</span></div></div></footer><script>const h=document.getElementById('siteHeader'),b=document.getElementById('menuBtn');if(b)b.addEventListener('click',()=>{const open=h.classList.toggle('open');b.textContent=open?'Fechar':'Menu';b.setAttribute('aria-expanded',String(open))});window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)};</script><script defer src="/_vercel/insights/script.js"></script>`}
function shell({title='VAELITH',description='VAELITH — Engenharia, arquitetura, construção e tecnologia.',canonical=SITE,active='',body='',jsonLd='',ogImage='',ogType='website',articlePublished='',articleModified='',author='',robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'}){
 const articleMeta=ogType==='article'?`${articlePublished?`<meta property="article:published_time" content="${esc(articlePublished)}">`:''}${articleModified?`<meta property="article:modified_time" content="${esc(articleModified)}">`:''}${author?`<meta name="author" content="${esc(author)}">`:''}`:'';
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#ffffff"><meta name="color-scheme" content="light"><meta name="robots" content="${esc(robots)}"><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><link rel="alternate" type="application/rss+xml" title="VAELITH" href="${SITE}/rss.xml"><link rel="stylesheet" href="/assets/editorial.css"><link rel="stylesheet" href="/assets/refinement.css"><link rel="stylesheet" href="/assets/visual-fixes.css"><link rel="icon" href="/favicon.svg" type="image/svg+xml">${googleTag}<meta property="og:site_name" content="VAELITH"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="${esc(ogType)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${ogImage?`<meta property="og:image" content="${esc(ogImage)}"><meta property="og:image:alt" content="${esc(title)}">`:''}${articleMeta}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}">${ogImage?`<meta name="twitter:image" content="${esc(ogImage)}">`:''}<title>${esc(title)} | VAELITH</title>${jsonLd?`<script type="application/ld+json">${jsonLd}</script>`:''}</head><body>${header(active)}${body}${footer()}</body></html>`;
}
module.exports={SITE,esc,navItems,brand,shell};
