const SITE='https://www.vaelithlabs.com.br';
const esc=(v='')=>String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const navItems=[['engenharia','Engenharia'],['arquitetura','Arquitetura'],['construcao','Construção'],['tecnologia','Tecnologia'],['infraestrutura','Infraestrutura'],['mercado','Mercado'],['gestao','Gestão'],['sustentabilidade','Sustentabilidade']];
const mark=`<svg class="mark" viewBox="0 0 1280 1280" aria-hidden="true"><path d="M240 276H332L632 787L938 276H1022L632 923Z" fill="currentColor"/><path d="M434 276H852L661 598H580L730 344H474Z" fill="currentColor"/></svg>`;
const brand=`<span class="brand">${mark}<span class="wordmark"><span class="wordmark-main">VAELITH</span><span class="wordmark-labs">LABS</span></span></span>`;
function header(active=''){
  const nav=navItems.map(([slug,name])=>`<a href="/categoria/${slug}" class="${active===slug?'active':''}">${name}</a>`).join('');
  return `<div class="topline"><div class="container"><span><strong>VAELITH NEWSROOM</strong> · Inteligência para o ambiente construído</span><span id="today">Brasil & Mundo</span></div></div><header class="site-header" id="siteHeader"><div class="container header-main"><a href="/" aria-label="VAELITH — início">${brand}</a><div class="header-meta"><a href="/eventos">Agenda</a><a href="/sobre">Sobre</a><a href="/autor/douglas-ornelas">Equipe</a><a href="/buscar" aria-label="Buscar no VAELITH">Buscar</a></div><button class="menu-btn" id="menuBtn" type="button" aria-controls="mainNav" aria-expanded="false">Menu</button></div><nav class="navbar" id="mainNav" aria-label="Navegação principal"><div class="container"><a href="/">Início</a>${nav}<a href="/eventos" class="${active==='eventos'?'active':''}">Agenda</a><a class="nav-search" href="/buscar">Buscar</a></div></nav></header>`;
}
function footer(){return `<footer class="footer"><div class="container"><div class="footer-grid"><div>${brand}<p>Notícias, análises e inteligência para quem projeta, constrói, gerencia e transforma o ambiente construído.</p></div><div><h4>Editorias</h4><p><a href="/categoria/engenharia">Engenharia</a><br><a href="/categoria/arquitetura">Arquitetura</a><br><a href="/categoria/construcao">Construção</a><br><a href="/categoria/tecnologia">Tecnologia</a><br><a href="/categoria/infraestrutura">Infraestrutura</a><br><a href="/categoria/mercado">Mercado</a></p></div><div><h4>Institucional</h4><p><a href="/sobre">Sobre a VAELITH</a><br><a href="/autor/douglas-ornelas">Equipe editorial</a><br><a href="/politica-editorial">Política editorial</a><br><a href="/privacidade">Privacidade</a><br><a href="/rss.xml">RSS</a><br><a href="mailto:labsvaelith@gmail.com">labsvaelith@gmail.com</a></p></div></div><div class="footer-bottom"><span>© 2026 VAELITH LABS. Todos os direitos reservados.</span><span>Conteúdo internacional contextualizado em português com atribuição da fonte.</span></div></div></footer><script>const h=document.getElementById('siteHeader'),b=document.getElementById('menuBtn');if(b)b.addEventListener('click',()=>{const open=h.classList.toggle('open');b.textContent=open?'Fechar':'Menu';b.setAttribute('aria-expanded',String(open))});const d=document.getElementById('today');if(d)d.textContent=new Intl.DateTimeFormat('pt-BR',{dateStyle:'full'}).format(new Date());</script>`}
function shell({title='VAELITH',description='VAELITH — Engenharia, arquitetura, construção e tecnologia.',canonical=SITE,active='',body='',jsonLd='',ogImage='',ogType='website',articlePublished='',articleModified='',author='',robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'}){
 const articleMeta=ogType==='article'?`${articlePublished?`<meta property="article:published_time" content="${esc(articlePublished)}">`:''}${articleModified?`<meta property="article:modified_time" content="${esc(articleModified)}">`:''}${author?`<meta name="author" content="${esc(author)}">`:''}`:'';
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0b0c0d"><meta name="color-scheme" content="dark"><meta name="robots" content="${esc(robots)}"><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><link rel="alternate" type="application/rss+xml" title="VAELITH Newsroom" href="${SITE}/rss.xml"><link rel="stylesheet" href="/assets/styles.css"><link rel="stylesheet" href="/assets/mobile.css"><link rel="stylesheet" href="/assets/premium.css"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><meta property="og:site_name" content="VAELITH"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="${esc(ogType)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${esc(canonical)}">${ogImage?`<meta property="og:image" content="${esc(ogImage)}"><meta property="og:image:alt" content="${esc(title)}">`:''}${articleMeta}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}">${ogImage?`<meta name="twitter:image" content="${esc(ogImage)}">`:''}<title>${esc(title)} | VAELITH</title>${jsonLd?`<script type="application/ld+json">${jsonLd}</script>`:''}</head><body>${header(active)}${body}${footer()}</body></html>`;
}
module.exports={SITE,esc,navItems,brand,shell};
