const content=require('./content');
const {SITE,esc,navItems,shell}=require('./layout');
const {card}=require('./cards');

const catDesc={
  engenharia:'Estruturas, projetos, materiais, inspeção, manutenção e prática técnica.',
  arquitetura:'Projetos, cidades, urbanismo, design e cultura do ambiente construído.',
  construcao:'Execução, produtividade, industrialização, métodos e cadeia produtiva.',
  tecnologia:'IA, BIM, automação, dados, equipamentos e Construction Tech.',
  infraestrutura:'Rodovias, ferrovias, pontes, energia, saneamento e ativos críticos.',
  mercado:'Crédito, investimentos, empresas, custos e indicadores da construção.',
  gestao:'Planejamento, riscos, contratos, pessoas, suprimentos e entrega de projetos.',
  sustentabilidade:'Carbono, energia, materiais, circularidade e resiliência.'
};
const catMeta={
  engenharia:'Notícias e análises de engenharia sobre estruturas, projetos, materiais, inspeção, manutenção, obras e prática técnica no Brasil e no mundo.',
  arquitetura:'Arquitetura, urbanismo, projetos, cidades, design e cultura do ambiente construído com contexto técnico e referências nacionais e internacionais.',
  construcao:'Construção civil, produtividade, métodos executivos, industrialização, canteiros, materiais e cadeia produtiva com foco profissional.',
  tecnologia:'IA, BIM, automação, dados, robótica, softwares e Construction Tech aplicados à engenharia, arquitetura e construção.',
  infraestrutura:'Infraestrutura de transportes, pontes, ferrovias, rodovias, energia, saneamento e ativos críticos com leitura técnica e de mercado.',
  mercado:'Mercado da construção, crédito, investimentos, empresas, custos, indicadores e movimentos econômicos que afetam o ambiente construído.',
  gestao:'Gestão de projetos e obras, planejamento, riscos, contratos, suprimentos, equipes, produtividade e tomada de decisão.',
  sustentabilidade:'Sustentabilidade na construção: carbono, energia, materiais, circularidade, rastreabilidade, resiliência e transição climática.'
};

function category(slug){
  const items=content.articles.filter(x=>x.categorySlug===slug).sort((a,b)=>b.date.localeCompare(a.date));if(!items.length)return null;
  const name=items[0].category;const other=navItems.filter(([s])=>s!==slug).slice(0,4).map(([s,n])=>`<a class="topic-chip" href="/categoria/${s}">${n}</a>`).join('');
  const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Editoria</div><h1>${esc(name)}</h1><p>${esc(catDesc[slug]||`Notícias e análises sobre ${name}.`)}</p></div></section><section class="section"><div class="container"><div class="section-head"><div><div class="kicker">Últimas</div><h2>Notícias de ${esc(name)}</h2></div><p>Conteúdo com fonte identificada, contexto técnico e leitura orientada a profissionais.</p></div><div class="list-grid">${items.map(card).join('')}</div><div class="topic-nav"><span>Explore também</span>${other}</div></div></section></main>`;
  const ld=JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:`${name} | VAELITH`,description:catMeta[slug]||catDesc[slug],url:`${SITE}/categoria/${slug}`,isPartOf:{'@type':'WebSite',name:'VAELITH',url:SITE}});
  return shell({title:name,description:catMeta[slug]||catDesc[slug],canonical:`${SITE}/categoria/${slug}`,active:slug,body,jsonLd:ld});
}

function events(slug=''){
  if(slug){
    const ev=content.events.find(x=>x.slug===slug);if(!ev)return null;
    const others=content.events.filter(x=>x.slug!==ev.slug).slice(0,4).map(x=>`<div class="sidebar-card"><a href="/eventos/${esc(x.slug)}"><div class="tag">${esc(x.category)}</div><h4>${esc(x.title)}</h4><div class="meta"><span>${esc(x.dateDisplay)}</span><span>${esc(x.location)}</span></div></a></div>`).join('');
    const body=`<main class="article-shell"><div class="container"><div class="breadcrumb"><a href="/">Início</a> / <a href="/eventos">Agenda</a> / Evento</div><div class="article-grid"><article><header class="article-header"><div class="tag">${esc(ev.category)} · AGENDA</div><h1>${esc(ev.title)}</h1><p class="article-dek">${esc(ev.summary)}</p><div class="article-info"><span>${esc(ev.dateDisplay)}</span><span>${esc(ev.location)}</span><span>Fonte: ${esc(ev.sourceName)}</span></div></header><div class="article-body"><h2>Por que acompanhar</h2><p>Eventos do setor funcionam como radar de tecnologias, novos métodos, movimentos de mercado e mudanças na prática profissional. A VAELITH acompanha encontros nacionais e internacionais relevantes para o ambiente construído.</p><div class="insight"><strong>VAELITH Agenda</strong><p>A proposta é acompanhar a agenda antes, durante e depois: antecipar temas, destacar anúncios e registrar os aprendizados mais relevantes para o setor.</p></div></div><div class="source-box"><h3>Informações oficiais</h3><p>Consulte data, programação, inscrições e eventuais alterações diretamente na fonte do evento.</p><a class="source-link" href="${esc(ev.sourceUrl)}" target="_blank" rel="noopener noreferrer">Acessar fonte oficial ↗</a></div></article><aside class="sidebar"><div class="sidebar-title">Outros eventos</div>${others}</aside></div></div></main>`;
    return shell({title:ev.title,description:ev.summary,canonical:`${SITE}/eventos/${ev.slug}`,active:'eventos',body,ogType:'article'});
  }
  const rows=[...content.events].sort((a,b)=>a.date.localeCompare(b.date)).map(ev=>`<a class="event-row" href="/eventos/${esc(ev.slug)}"><div class="date">${esc(ev.dateDisplay)}</div><div><div class="tag">${esc(ev.category)}</div><h3>${esc(ev.title)}</h3><p>${esc(ev.summary)}</p></div><div class="place">${esc(ev.location)}</div></a>`).join('');
  const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Brasil & Mundo</div><h1>VAELITH Agenda</h1><p>Feiras, congressos, conferências e encontros relevantes para engenharia, arquitetura, construção, infraestrutura, gestão, BIM e tecnologia.</p></div></section><section class="section"><div class="container"><div class="event-grid"><div class="event-list">${rows}</div><aside class="radar"><div class="tag">Radar VAELITH</div><h3>Eventos que merecem atenção.</h3><p>A agenda é verificada em fontes oficiais e organizada para ajudar profissionais a acompanhar os movimentos do setor.</p><div class="radar-list"><div>Datas e locais identificados</div><div>Fonte oficial de cada evento</div><div>Cobertura nacional e internacional</div></div></aside></div></div></section></main>`;
  return shell({title:'Agenda de eventos',description:'Agenda VAELITH de eventos de engenharia, construção, arquitetura, BIM e tecnologia.',canonical:`${SITE}/eventos`,active:'eventos',body});
}

function about(){const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Institucional</div><h1>Sobre a VAELITH</h1><p>Informação técnica, visão global e contexto para o ambiente construído.</p></div></section><section class="section"><div class="container"><div class="article-grid"><article class="article-body"><h2>O que é a VAELITH</h2><p>A VAELITH é uma plataforma editorial independente voltada à engenharia, arquitetura, construção, infraestrutura, gestão e tecnologia. A missão é transformar informação dispersa em conteúdo claro, verificável e útil para quem toma decisões no ambiente construído.</p><h2>Como trabalhamos</h2><p>Priorizamos fontes primárias, documentos oficiais e veículos especializados reconhecidos. Conteúdo internacional é contextualizado em português com identificação da origem. Notícias factuais e leitura editorial são separadas de forma explícita.</p><h2>O que queremos entregar</h2><p>Além de notícias, a VAELITH evolui para análises, projetos, dados, agenda setorial e ferramentas digitais. O objetivo é ser uma fonte recorrente de inteligência profissional, não apenas um agregador de manchetes.</p><h2>Transparência e correções</h2><p>Erros relevantes são corrigidos quando identificados. Sugestões de pauta, pedidos de correção, parcerias e contato institucional podem ser encaminhados ao editorial.</p></article><aside class="sidebar"><div class="source-box"><h3>Responsável</h3><p><strong>Douglas Ornelas</strong><br>Engenheiro Civil · CREA-MG 226484/D<br>MBA em Gestão de Projetos.</p><a class="source-link" href="/autor/douglas-ornelas">Perfil editorial →</a></div><div class="source-box"><h3>Contato editorial</h3><p>Sugestões de pauta, correções e parcerias.</p><a class="source-link" href="mailto:labsvaelith@gmail.com">labsvaelith@gmail.com</a></div></aside></div></div></section></main>`;const ld=JSON.stringify({'@context':'https://schema.org','@type':'AboutPage',name:'Sobre a VAELITH',url:`${SITE}/sobre`,mainEntity:{'@type':'NewsMediaOrganization',name:'VAELITH',url:SITE,email:'labsvaelith@gmail.com'}});return shell({title:'Sobre a VAELITH',description:'Conheça a missão, critérios, responsável editorial e padrão de produção de conteúdo da VAELITH.',canonical:`${SITE}/sobre`,body,jsonLd:ld});}
function editorial(){const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Institucional</div><h1>Política editorial</h1><p>Critérios de fonte, autoria, tradução, inteligência artificial, correção e conteúdo patrocinado.</p></div></section><section class="section"><div class="container"><article class="article-body institutional-copy"><h2>Fontes e verificação</h2><p>A VAELITH prioriza fontes primárias, documentos oficiais, empresas responsáveis por projetos, entidades técnicas e veículos especializados reconhecidos. Toda notícia baseada em fonte externa identifica a origem de forma visível.</p><h2>Notícia, análise e opinião</h2><p>Informações factuais são apresentadas como notícia. Interpretações e contexto produzido pela VAELITH são identificados como leitura editorial ou análise. Opiniões assinadas devem ser claramente distinguidas do noticiário.</p><h2>Conteúdo internacional</h2><p>Quando a fonte original está em outro idioma, a VAELITH não reproduz a publicação. Produz uma síntese própria em português, preserva a atribuição e adiciona contexto relevante para o setor brasileiro.</p><h2>Uso de inteligência artificial</h2><p>Ferramentas de IA podem apoiar pesquisa, organização, tradução e estruturação de conteúdo. Elas não substituem a necessidade de fonte identificada, verificação factual e responsabilidade editorial sobre o material publicado.</p><h2>Imagens</h2><p>Imagens ilustrativas são tratadas como tal. A prioridade editorial é utilizar imagens oficiais, autorizadas ou licenciadas, com crédito e legenda sempre que disponíveis.</p><h2>Correções</h2><p>Correções relevantes são incorporadas assim que identificadas. Solicitações podem ser encaminhadas para labsvaelith@gmail.com com o link da publicação e a informação que precisa ser revisada.</p><h2>Publicidade e conteúdo patrocinado</h2><p>Conteúdo comercial, publieditorial ou patrocinado é identificado de forma clara e não interfere nos critérios de seleção de notícias e análises editoriais.</p></article></div></section></main>`;return shell({title:'Política editorial',description:'Critérios editoriais, transparência, fontes, uso de IA, imagens, publicidade e correções na VAELITH.',canonical:`${SITE}/politica-editorial`,body});}
function privacy(){const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Privacidade</div><h1>Política de privacidade</h1><p>Como a VAELITH trata dados técnicos, contato editorial e inscrições na newsletter.</p></div></section><section class="section"><div class="container"><article class="article-body institutional-copy"><p>A VAELITH respeita a privacidade dos visitantes e busca limitar a coleta de dados ao necessário para operação, segurança e melhoria da plataforma.</p><h2>Newsletter</h2><p>Quando você se inscreve no VAELITH Briefing, o e-mail informado é utilizado exclusivamente para envio do conteúdo solicitado e comunicações relacionadas. O cancelamento pode ser solicitado a qualquer momento.</p><h2>Dados técnicos</h2><p>A infraestrutura de hospedagem e segurança pode processar informações técnicas como endereço IP, navegador, dispositivo, data e horário de acesso para entrega do serviço, prevenção de abuso e diagnóstico de falhas.</p><h2>Compartilhamento e venda</h2><p>A VAELITH não comercializa dados pessoais de visitantes. Prestadores técnicos podem processar dados estritamente para fornecer serviços de infraestrutura, segurança, hospedagem ou comunicação.</p><h2>Contato</h2><p>Questões relacionadas à privacidade podem ser encaminhadas para labsvaelith@gmail.com.</p></article></div></section></main>`;return shell({title:'Política de privacidade',description:'Política de privacidade, newsletter e tratamento de dados pessoais da VAELITH.',canonical:`${SITE}/privacidade`,body});}
function author(){const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Equipe editorial</div><h1>Douglas Ornelas</h1><p>Engenheiro Civil e responsável pela orientação técnica e editorial da VAELITH.</p></div></section><section class="section"><div class="container"><div class="article-grid"><article class="article-body"><p>Douglas Ornelas é engenheiro civil com MBA em Gestão de Projetos. A VAELITH nasceu da sua paixão por engenharia, construção e infraestrutura — um espaço criado para reunir e contextualizar as notícias mais relevantes do setor.</p><h2>Áreas de interesse editorial</h2><p>Gestão de obras, planejamento, infraestrutura, retrofit, tecnologia aplicada à construção, BIM, inteligência artificial, produtividade, contratos, riscos e tomada de decisão em projetos.</p></article><aside class="sidebar"><div class="source-box"><h3>Credenciais</h3><p>Engenharia Civil<br>CREA-MG 226484/D<br>MBA em Gestão de Projetos</p></div><div class="source-box"><h3>Contato</h3><a class="source-link" href="mailto:labsvaelith@gmail.com">labsvaelith@gmail.com</a></div></aside></div></div></section></main>`;const ld=JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Douglas Ornelas',jobTitle:'Engenheiro Civil',url:`${SITE}/autor/douglas-ornelas`,worksFor:{'@type':'Organization',name:'VAELITH',url:SITE}});return shell({title:'Douglas Ornelas',description:'Perfil editorial de Douglas Ornelas, engenheiro civil e responsável técnico-editorial da VAELITH.',canonical:`${SITE}/autor/douglas-ornelas`,body,jsonLd:ld});}
function search(q=''){const query=String(q||'').trim();const needle=query.toLocaleLowerCase('pt-BR');const results=query?content.articles.filter(a=>[a.title,a.dek,a.category,a.region,a.sourceName,...(a.body||[])].join(' ').toLocaleLowerCase('pt-BR').includes(needle)).sort((a,b)=>b.date.localeCompare(a.date)):[];const resultHtml=query?(results.length?`<div class="search-count">${results.length} resultado${results.length===1?'':'s'} para “${esc(query)}”</div><div class="list-grid search-results">${results.map(card).join('')}</div>`:`<div class="empty-state"><h2>Nenhum resultado encontrado.</h2><p>Tente uma categoria, empresa, tecnologia, obra ou tema diferente.</p></div>`):`<div class="empty-state"><h2>Pesquise o acervo VAELITH.</h2><p>Busque por engenharia, BIM, infraestrutura, IA, gestão, mercado e outros temas.</p></div>`;const body=`<main><section class="page-hero search-hero"><div class="container"><div class="kicker">Pesquisa</div><h1>Buscar no VAELITH</h1><form class="search-form" action="/buscar" method="get"><label class="sr-only" for="q">Pesquisar</label><input id="q" name="q" value="${esc(query)}" placeholder="Busque por tema, empresa, obra ou tecnologia"><button type="submit">Buscar</button></form></div></section><section class="section"><div class="container">${resultHtml}</div></section></main>`;return shell({title:query?`Busca: ${query}`:'Buscar',description:'Pesquise notícias, análises, projetos e temas no acervo editorial da VAELITH.',canonical:`${SITE}/buscar`,robots:'noindex,follow',body});}
function mediaKit(){const body=`<main><section class="page-hero"><div class="container"><div class="kicker">Parcerias</div><h1>Mídia kit VAELITH</h1><p>Conecte sua marca a profissionais de engenharia, construção, arquitetura, infraestrutura, gestão e tecnologia.</p></div></section><section class="section"><div class="container"><div class="media-grid"><article class="article-body"><h2>Ambiente editorial especializado</h2><p>A VAELITH oferece formatos publicitários integrados a um portal técnico, com separação clara entre conteúdo editorial e comercial.</p><h2>Formatos disponíveis</h2><div class="media-products"><div><strong>Leaderboard</strong><span>Faixa premium em páginas de alto tráfego.</span></div><div><strong>Native display</strong><span>Bloco visual identificado como publicidade.</span></div><div><strong>Newsletter</strong><span>Patrocínio do VAELITH Briefing.</span></div><div><strong>Conteúdo patrocinado</strong><span>Publieditorial identificado e separado do noticiário.</span></div></div><h2>Segmentos aderentes</h2><p>Construtoras, incorporadoras, fabricantes de materiais, softwares, BIM, equipamentos, segurança, energia, infraestrutura, universidades, eventos e serviços B2B.</p></article><aside class="sidebar"><div class="source-box"><h3>Comercial</h3><p>Solicite proposta, formatos e disponibilidade.</p><a class="source-link" href="mailto:labsvaelith@gmail.com?subject=Mídia kit VAELITH">labsvaelith@gmail.com</a></div><div class="source-box"><h3>Transparência</h3><p>Publicidade e conteúdo patrocinado não interferem nos critérios editoriais.</p><a class="source-link" href="/politica-editorial">Política editorial →</a></div></aside></div></div></section></main>`;return shell({title:'Mídia kit',description:'Publicidade, patrocínios e formatos comerciais da VAELITH para marcas de engenharia, construção, tecnologia e infraestrutura.',canonical:`${SITE}/midia-kit`,body});}
function info(which){if(which==='about')return about();if(which==='editorial')return editorial();if(which==='privacy')return privacy();return null;}
module.exports={category,events,info,author,search,mediaKit};
