const content=require('./content');const {SITE,esc,shell}=require('./layout');
module.exports=function renderArticle(slug){
 const a=content.articles.find(x=>x.slug===slug);if(!a)return null;
 const related=content.articles.filter(x=>x.categorySlug===a.categorySlug&&x.slug!==a.slug).sort((x,y)=>y.date.localeCompare(x.date)).slice(0,3);
 const side=related.map(x=>`<div class="sidebar-card"><a href="/noticias/${esc(x.slug)}"><div class="tag">${esc(x.category)}</div><h4>${esc(x.title)}</h4><div class="meta"><span>${esc(x.dateDisplay)}</span></div></a></div>`).join('');
 const paragraphs=a.body.map(p=>`<p>${esc(p)}</p>`).join('');
 const translated=a.sourceLanguage&&a.sourceLanguage!=='Português';
 const canonical=`${SITE}/noticias/${a.slug}`;
 const ld=JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'NewsArticle','@id':`${canonical}#article`,headline:a.title,description:a.dek,image:[a.image],datePublished:a.date,dateModified:a.date,inLanguage:'pt-BR',isAccessibleForFree:true,articleSection:a.category,mainEntityOfPage:canonical,author:{'@type':'Organization',name:'VAELITH Editorial',url:`${SITE}/sobre`},publisher:{'@type':'NewsMediaOrganization',name:'VAELITH',url:SITE,logo:{'@type':'ImageObject',url:`${SITE}/favicon.svg`}}},{'@type':'BreadcrumbList','@id':`${canonical}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'Início',item:SITE},{'@type':'ListItem',position:2,name:a.category,item:`${SITE}/categoria/${a.categorySlug}`},{'@type':'ListItem',position:3,name:a.title,item:canonical}]}]});
 const body=`<main class="article-shell"><div class="container"><div class="breadcrumb"><a href="/">Início</a> / <a href="/categoria/${esc(a.categorySlug)}">${esc(a.category)}</a> / Notícia</div><div class="article-grid"><article><header class="article-header"><div class="tag">${esc(a.category)} · ${esc(a.region)}</div><h1>${esc(a.title)}</h1><p class="article-dek">${esc(a.dek)}</p><div class="article-info"><span><a href="/sobre">VAELITH Editorial</a></span><span>${esc(a.dateDisplay)}</span><span>${esc(a.category)} · ${esc(a.region)}</span><span>Fonte: ${esc(a.sourceName)}</span>${translated?'<span>Fonte internacional · contextualizada em português</span>':''}</div></header><figure class="article-figure"><img class="article-hero" src="${esc(a.image)}" alt="${esc(a.title)}" width="1280" height="720" fetchpriority="high" loading="eager" decoding="async"><figcaption>Imagem ilustrativa usada na composição editorial. A informação factual da matéria é atribuída à fonte indicada.</figcaption></figure><div class="article-body">${paragraphs}<div class="insight"><strong>Leitura VAELITH</strong><p>Esta matéria é uma síntese editorial própria baseada na fonte identificada. O objetivo é oferecer contexto técnico ao setor brasileiro sem reproduzir o texto original.</p></div></div><div class="source-box"><h3>Fonte e transparência</h3><p>Fonte principal: <strong>${esc(a.sourceName)}</strong>. ${translated?'A publicação original está em outro idioma; a VAELITH produziu uma síntese em português e adicionou contexto editorial.':'A VAELITH produziu uma síntese própria e adicionou contexto editorial.'}</p><a class="source-link" href="${esc(a.sourceUrl)}" target="_blank" rel="noopener noreferrer">Consultar fonte original ↗</a></div></article><aside class="sidebar"><div class="sidebar-title">Mais em ${esc(a.category)}</div>${side}<div class="source-box"><h3>Correções</h3><p>Encontrou alguma informação que precisa de ajuste?</p><a class="source-link" href="mailto:labsvaelith@gmail.com?subject=Correção editorial — ${encodeURIComponent(a.title)}">Falar com o editorial →</a></div></aside></div></div></main>`;
 return shell({title:a.title,description:a.dek,canonical,active:a.categorySlug,body,jsonLd:ld,ogImage:a.image,ogType:'article',articlePublished:a.date,articleModified:a.date,author:'VAELITH Editorial'});
}
