function html(title,message,status=200){return {status,body:`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${title} | VAELITH</title><style>body{margin:0;background:#0b0c0d;color:#f4f5f6;font-family:Arial,sans-serif}.wrap{max-width:640px;margin:12vh auto;padding:32px}.box{border:1px solid #2a2f33;padding:32px;background:#101214}.k{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#d8ff3e;font-weight:700}h1{font-size:36px;line-height:1.1;margin:10px 0 16px}p{color:#b6bbc0;line-height:1.6}a{display:inline-block;margin-top:14px;color:#d8ff3e;text-decoration:none;font-weight:700}</style></head><body><div class="wrap"><div class="box"><div class="k">VAELITH Briefing</div><h1>${title}</h1><p>${message}</p><a href="/">Voltar para o portal →</a></div></div></body></html>`};}
const headers=apiKey=>({Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'});
async function addExistingToSegment(apiKey,email,segmentId){if(!segmentId)return;const r=await fetch(`https://api.resend.com/contacts/${encodeURIComponent(email)}/segments/${encodeURIComponent(segmentId)}`,{method:'POST',headers:headers(apiKey)});if(!r.ok){const detail=await r.text();console.error('NEWSLETTER_SEGMENT_ERROR',r.status,detail.slice(0,300));throw new Error('segment');}}
module.exports=async(req,res)=>{
  res.setHeader('Cache-Control','no-store');
  if(req.method!=='POST'){res.statusCode=405;res.setHeader('Allow','POST');return res.end('Method Not Allowed');}
  let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>4096){res.statusCode=413;return res.end('Formulário muito grande');}}const params=new URLSearchParams(body);const email=String(params.get('email')||'').trim().toLowerCase();const consent=params.get('consent');
  if(consent!=='yes'||email.length>254||!/^\S+@\S+\.\S+$/.test(email)){const out=html('Não foi possível concluir','Confira o e-mail informado e confirme o consentimento para receber o briefing.',400);res.statusCode=out.status;res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(out.body);}
  const apiKey=process.env.RESEND_API_KEY;const segmentId=process.env.RESEND_SEGMENT_ID||process.env.RESEND_AUDIENCE_ID;
  if(!apiKey||!segmentId){console.error('NEWSLETTER_CONFIG_MISSING');const out=html('Inscrição temporariamente indisponível','O serviço de cadastro ainda precisa ser conectado ao provedor de e-mail. Tente novamente em breve.',503);res.statusCode=out.status;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(out.body);}
  try{
    const payload={email,unsubscribed:false};if(segmentId)payload.segments=[{id:segmentId}];
    const r=await fetch('https://api.resend.com/contacts',{method:'POST',headers:headers(apiKey),body:JSON.stringify(payload)});
    if(!r.ok){const detail=await r.text();if(r.status===409){if(segmentId)await addExistingToSegment(apiKey,email,segmentId);}else{console.error('NEWSLETTER_RESEND_ERROR',r.status,detail.slice(0,300));throw new Error('provider');}}
    const out=html('Inscrição confirmada','Seu e-mail foi cadastrado no VAELITH Briefing. Você receberá as principais notícias do setor e poderá cancelar quando quiser.');res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(out.body);
  }catch(err){console.error('NEWSLETTER_ERROR',err&&err.message?err.message:err);const out=html('Não foi possível concluir','O serviço de inscrição encontrou um erro temporário. Tente novamente em alguns minutos.',502);res.statusCode=out.status;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(out.body);}
};
